mac_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
      PKG_CONFIG_PATH: /opt/homebrew/opt/libffi/lib/pkgconfig
      PATH: /opt/homebrew/opt/ccache/libexec:${PATH}
  deps_script: |
    brew install autoconf automake libtool pkg-config openssl libffi ccache compiledb
  git_submodules_script: |
    git submodule update --init --recursive
  cirrus_cli_script: |
    find . -name '*.sh' -exec chmod +x {} \;
    find . -name 'configure' -exec chmod +x {} \;
    chmod +x bin/natalie
  build_script: |
    rake --trace
  run_script: |
    bin/natalie examples/pact-cli.rb || true
  compile_script: |
    mkdir -p pkg
    bin/natalie -c pkg/pact-cli examples/pact-cli.rb
  binary_artifacts:
    paths: ["pkg/pact-cli"]

mac_intel_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
      PKG_CONFIG_PATH: /usr/local/opt/libffi/lib/pkgconfig
      PATH: /usr/local/opt/ruby/bin:/usr/local/homebrew/bin:/usr/local/opt/ccache/libexec:${PATH}
  rosetta_script: |
    softwareupdate --install-rosetta --agree-to-license
  ibrew_script: |
    arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "alias ibrew='arch -x86_64 /usr/local/bin/brew'" >> ~/.zprofile
  deps_script: |
    arch -x86_64 /usr/local/bin/brew install ruby autoconf automake libtool pkg-config openssl libffi ccache compiledb
  git_submodules_script: |
    git submodule update --init --recursive
  cirrus_cli_script: |
    find . -name '*.sh' -exec chmod +x {} \;
    find . -name 'configure' -exec chmod +x {} \;
    chmod +x bin/natalie
  build_script: |
    arch -x86_64 rake --trace
  run_script: |
    arch -x86_64 bin/natalie examples/pact-cli.rb || true
  compile_script: |
    mkdir -p pkg
    arch -x86_64 bin/natalie -c pkg/pact-cli examples/pact-cli.rb
  binary_artifacts:
    paths: ["pkg/pact-cli"]

linux_arm_task:
  arm_container:
    image: ruby:3.2.2-bookworm
  env:
    LC_ALL: C.UTF-8
    LLVM_CONFIG: /usr/lib/llvm-14/bin/llvm-config
    CC: gcc
    CXX: g++
    NAT_CXX_FLAGS: '-DNAT_GC_GUARD '
  deps_script: |
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q build-essential autoconf libtool clang lcov clang-tidy libclang-dev lldb python3 python3-pip ccache
    pip3 install compiledb || pip3 install compiledb --break-system-packages
    gem install bundler --no-doc
  git_submodules_script: |
    git submodule update --init --recursive
  build_script: |
    rake --trace
  run_script: |
    bin/natalie examples/pact-cli.rb || true
  compile_script: |
    mkdir -p pkg
    bin/natalie -c pkg/pact-cli examples/pact-cli.rb
  binary_artifacts:
    paths: ["pkg/pact-cli"]

linux_intel_task:
  container:
    image: ruby:3.2.2-bookworm
  deps_script: |
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q build-essential autoconf libtool clang lcov clang-tidy libclang-dev lldb python3 python3-pip ccache
    pip3 install compiledb || pip3 install compiledb --break-system-packages
    gem install bundler --no-doc
  git_submodules_script: |
    git submodule update --init --recursive
  build_script: |
    rake --trace
  run_script: |
    bin/natalie examples/pact-cli.rb || true
  compile_script: |
    mkdir -p pkg
    bin/natalie -c pkg/pact-cli examples/pact-cli.rb
  binary_artifacts:
    paths: ["pkg/pact-cli"]

# alpine_arm_task:
#   arm_container:
#     image: ruby:3.2.2-alpine3.18
#   env:
#     LC_ALL: C.UTF-8
#     LLVM_CONFIG: /usr/bin/llvm-config
#     CC: clang
#     CXX: clang++
#     # NAT_CXX_FLAGS: '-DNAT_GC_GUARD '
#   deps_script: |
#     mkdir -p /tmp
#     chown -R $(whoami) /tmp
#     apk add --no-cache build-base autoconf libtool clang llvm-libunwind llvm-dev llvm-static clang-extra-tools clang-dev lldb python3 py3-pip ccache git automake gcc g++ make ccache
#     ls /usr/bin/llvm-config
#     pip3 install compiledb || pip3 install compiledb --break-system-packages
#     gem install bundler --no-doc
#   git_submodules_script: |
#     git submodule update --init --recursive
#   build_script: |
#     rake --trace
#   run_script: |
#     bin/natalie examples/pact-cli.rb || true
#   compile_script: |
#     mkdir -p pkg
#     bin/natalie -c pkg/pact-cli examples/pact-cli.rb
#   binary_artifacts:
#     paths: ["pkg/pact-cli"]
# alpine_intel_task:
#   container:
#     image: ruby:3.2.2-alpine3.18
#   env:
#     LC_ALL: C.UTF-8
#     LLVM_CONFIG: /usr/bin/llvm-config
#     CC: clang
#     CXX: clang++
#     NAT_CXX_FLAGS: '-DNAT_GC_GUARD '
#   deps_script: |
#     apk add --no-cache build-base autoconf libtool clang llvm-libunwind llvm-dev llvm-static clang-extra-tools clang-dev lldb python3 py3-pip ccache git automake gcc g++ make ccache
#     pip3 install compiledb || pip3 install compiledb --break-system-packages
#     gem install bundler --no-doc
#   git_submodules_script: |
#     git submodule update --init --recursive
#   build_script: |
#     rake --trace
#   run_script: |
#     bin/natalie examples/pact-cli.rb || true
#   compile_script: |
#     mkdir -p pkg
#     bin/natalie -c pkg/pact-cli examples/pact-cli.rb
#   binary_artifacts:
#     paths: ["pkg/pact-cli"]
